//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автовокзал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kor
    {
        public int Id { get; set; }
        public Nullable<int> Routes_Number { get; set; }
        public string Data { get; set; }
        public string C_Departure { get; set; }
        public string C_Departure_Time { get; set; }
        public string C_Destination { get; set; }
        public string C_Destination_Time { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
