//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автовокзал
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class avtovokEntities : DbContext
    {
        public avtovokEntities()
            : base("name=avtovokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Town> Town { get; set; }
        public virtual DbSet<Village> Village { get; set; }
        public virtual DbSet<Rout> Rout { get; set; }
        public virtual DbSet<Stopover> Stopover { get; set; }
        public virtual DbSet<Kor> Kor { get; set; }
    }
}
