//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автовокзал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rout
    {
        public int Rout_ID { get; set; }
        public Nullable<int> Routes_number { get; set; }
        public string Otk { get; set; }
        public string Vrem_otp { get; set; }
        public Nullable<int> Town_ID { get; set; }
        public string Vrem_Prib { get; set; }
        public Nullable<int> Kol { get; set; }
        public string Vrem_Prib_NCH { get; set; }
        public string Info { get; set; }
    }
}
