//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автовокзал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Routes
    {
        public int Routes_ID { get; set; }
        public Nullable<int> Routes_Number { get; set; }
        public string Otkuda { get; set; }
        public string Vremya_otpravlenya { get; set; }
        public Nullable<int> Town_ID { get; set; }
        public string Vremya_Pribitiya { get; set; }
        public Nullable<int> Kolichestvo_svob_biletov { get; set; }
        public string VreM_Prin_Nab { get; set; }
        public string Info { get; set; }
    }
}
