//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace автовокзал
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stopover
    {
        public int Stopover_ID { get; set; }
        public Nullable<int> Village_ID { get; set; }
        public Nullable<int> Routes_ID { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
